pull_request_rules:
- actions:
    queue: ''
  conditions:
  - base=20230808113215/test_the_head_of_train_is_not_the_expected_pull_request/main
  name: default merge
queue_rules:
- merge_conditions:
  - check-success=my_one_minute_CI
  name: urgent
  queue_conditions:
  - label=urgent
- name: standard
  queue_conditions:
  - check-success=my_one_minute_CI
