pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - label=queue
  name: default merge
queue_rules:
- name: default
  routing_conditions:
  - base=20230615133816/test_merging_a_stack/main
