pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - base=20230614065923/test_timeout_checks/main
  - label=queue
  name: merge default
queue_rules:
- checks_timeout: 10 m
  merge_conditions:
  - status-success=continuous-integration/fake-ci
  name: default
