pull_request_rules:
- actions:
    merge:
      method: merge
  conditions:
  - base=20230524095929/test_merge_custom_msg_merge/main
  - status-success=continuous-integration/fake-ci
  name: Merge on main
