pull_request_rules:
- actions:
    queue:
      name: queue_1
  conditions:
  - base=20231116163720/test_queue_rule_changed/main
  name: toto
queue_rules:
- merge_conditions:
  - base=20231116163720/test_queue_rule_changed/main
  - check-success=continuous-integration/fake-ci
  name: queue_1
- merge_conditions:
  - base=20231116163720/test_queue_rule_changed/main
  - check-success=continuous-integration/fake-ci
  name: queue_3
