pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - base=20230614085443/test_unsuccessful_checks_failed/main
  - label=queue
  name: merge default
queue_rules:
- checks_timeout: 10 m
  merge_conditions:
  - status-success=continuous-integration/fake-ci
  name: default
