pull_request_rules:
- actions:
    queue: ''
  conditions:
  - base=20230808152539/test_the_head_of_train_is_not_the_expected_pull_request/main
  name: default merge
queue_rules:
- name: urgent
  queue_conditions:
  - label=urgent
- name: standard
  queue_conditions:
  - label=standard
