pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - label=go_merge
  name: Merge on main
queue_rules:
- merge_conditions:
  - status-success=continuous-integration/fake-ci
  name: default
