pull_request_rules:
- actions:
    queue: ''
  conditions:
  - base=20230809084839/test_the_head_of_train_is_not_the_expected_pull_request/main
  name: default merge
queue_rules:
- name: default
  priority_rules:
  - conditions:
    - label=urgent
    name: high priority
    priority: high
