pull_request_rules:
- actions:
    merge:
      method: rebase
  conditions:
  - base=20231016160600/test_rebase/main
  - status-success=continuous-integration/fake-ci
  - '#approved-reviews-by>=1'
  name: Merge on main
