pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - base=20230613132546/test_failed_checks/main
  - label=queue
  name: merge default
queue_rules:
- merge_conditions:
  - status-success=continuous-integration/fake-ci
  name: default
