pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - base=main
  name: Merge on main
queue_rules:
- merge_conditions:
  - status-success=continuous-integration/fake-ci
  name: default
