pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - label=queue
  name: default merge
queue_rules:
- merge_conditions:
  - base=20230615073907/test_merging_a_astack/main
  name: default
