pull_request_rules:
- actions:
    queue:
      name: foo
  conditions:
  - check-success=Continuous Integration/unit-tests
  name: queue
queue_rules:
- merge_conditions:
  - check-success=Continuous Integration/unit-tests
  name: foo
