pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - base=20230517141659/test_sha_collision_after_pr_synchronization/main
  - label=queue
  name: default merge
queue_rules:
- conditions:
  - label=merge
  name: default
