pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - base=20231016185202/test_queue_command_after_action_queue/main
  - label=queue
  name: Merge on queue label
queue_rules:
- conditions: []
  name: default
