pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - base=20230614085716/test_unsuccessful_checks_failed/main
  - label=queue
  name: merge default
queue_rules:
- merge_conditions:
  - status-success=continuous-integration/fake-ci
  - status-success=continuous-integration/fake-ci_2
  name: default
