pull_request_rules:
- actions: {}
  conditions: []
  name: noop
queue_rules:
- allow_inplace_checks: false
  conditions:
  - base=20230608142518/test_pull_request_init_summary/main
  - check-success=continuous-integration/fake-ci
  name: foo
