pull_request_rules:
- actions:
    queue:
      name: foo
  conditions:
  - base=20230929123557/test_no_name_for_now/main
  name: queue
queue_rules:
- merge_conditions:
  - check-success=Continuous Integration/unit-tests
  name: foo
