pull_request_rules:
- actions:
    queue:
      name: queue_2
  conditions:
  - base=20231116165205/TQAWPEItest_queue_rule_vanish/main
  name: default merge
queue_rules:
- merge_conditions:
  - base=20231116165205/TQAWPEItest_queue_rule_vanish/main
  - check-success=continuous-integration/fake-ci
  name: queue_1
- merge_conditions:
  - base=20231116165205/TQAWPEItest_queue_rule_vanish/main
  - check-success=continuous-integration/fake-ci
  name: queue_2
