pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - base=20230517151646/test_sha_collision_after_pr_synchronization/main
  - label=queue
  name: default merge
queue_rules:
- merge_conditions:
  - or:
    - status-success=continuous-integration/fake-ci
    - label=merge
  name: default
